### ISSUE TITLE
Converting hijri months with 30 days

### ISSUE THREAD

**Issue by aalsaedi** [dralshehri/hijri-converter#2]
Thanks for this library.

I don't know why the function does not accept converting hijri months over 29 days, as sometimes it is 30.

Error message: 
"raise ValueError(f"day must be in 1..{month_length} for month")

ValueError: day must be in 1..29 for month"

**Comment by dralshehri** [comment]
Is it happening with specific date? Could you show me an example?

**Comment by aalsaedi** [comment]
This is the date I'm converting: 30-12-1433. It's equivalent to 15-11-2012 based on an online tool for Umm Alqura Calender.

Thanks

**Comment by dralshehri** [comment]
I have to say that the official online converter (http://www.ummulqura.org.sa) is unfortunately not 100% accurate. Using your example of 30-12-1433, converting 01-01-1434 will give you the same result of 15-11-2012.
![Screen Shot 2020-02-02 at 10 56 39 PM](https://user-images.githubusercontent.com/542855/73614373-60296200-460f-11ea-988a-bb2534c84cfb.png)
![Screen Shot 2020-02-02 at 10 57 06 PM](https://user-images.githubusercontent.com/542855/73614374-615a8f00-460f-11ea-8107-10d45711bff0.png)

In contrast, the hijri-converter package conversion is based on several original sources, including official printed umm al-Qura calendars, official governmental comparative calendars, and the umm al-Qura weekly newspaper. That's why I claim it's 100% accuracy.

The conclusion is that converting 30-12-1433 is not possible because month 12 of year 1433 AH is only 29 days long. That's why you get the exception.

If you're interested you may check the following link to confirm that:
https://www.staff.science.uu.nl/~gent0113/islam/downloads/umm_al_qura_1420_1450.pdf

Thanks for raising this issue!
